---
kind: pipeline
name: lint

steps:
- name: lint
  image: miki725/pre-commit

trigger:
  ref:
    - refs/heads/master
    - refs/pull/*/head

---
kind: pipeline
name: deploy

steps:
- name: deploy
  image: docker/compose:1.24.1
  environment:
    COMPOSE_PROJECT_NAME: sda-react
    MOUNT_PATH: /tmp/app
    INSTAGRAM_SECRET:
      from_secret:  INSTAGRAM_SECRET
  volumes:
    - name: docker_sock
      path: /var/run/docker.sock
  commands:
    - docker-compose build --pull
    - docker-compose up -d

trigger:
  ref:
    - refs/heads/master

volumes:
  - name: docker_sock
    host:
      path: /var/run/docker.sock

---
kind: secret
name: INSTAGRAM_SECRET
get:
  path: drone/data/firstrussianny/SDA-React
  name: INSTAGRAM_SECRET

---
kind: signature
hmac: b3c60a626acf7860132247a5fdabe354a0b0c1b135fc8eb8a1b2168507e3f902

...
