---
kind: pipeline
name: lint

steps:
- name: lint
  image: miki725/pre-commit

trigger:
  ref:
    - refs/heads/master
    - refs/pull/*/head

---
kind: pipeline
name: deploy

steps:
- name: deploy
  image: docker/compose:1.24.1
  environment:
    DOCKER_TLS_VERIFY: 1
    DOCKER_CERT_PATH: /tmp/docker-certs
    DOCKER_MACHINE_NAME: firstrussianny
    COMPOSE_PROJECT_NAME: sda-react
    MOUNT_PATH: /tmp/app
    PUBLIC_PORT: "172.17.0.1:8080"
    API_SITE_URL:
      from_secret:  API_SITE_URL
    DOCKER_HOST:
      from_secret: DOCKER_HOST
    DOCKER_CA_CERT:
      from_secret: DOCKER_CA_CERT
    DOCKER_CLIENT_CERT:
      from_secret: DOCKER_CLIENT_CERT
    DOCKER_CLIENT_KEY:
      from_secret: DOCKER_CLIENT_KEY
  commands:
    - mkdir -p $DOCKER_CERT_PATH
    - printenv DOCKER_CA_CERT > $DOCKER_CERT_PATH/ca.pem
    - printenv DOCKER_CLIENT_CERT > $DOCKER_CERT_PATH/cert.pem
    - printenv DOCKER_CLIENT_KEY > $DOCKER_CERT_PATH/key.pem
    - docker-compose build --pull
    - docker-compose up -d
    - timeout -t 60 docker-compose logs -f app || true

trigger:
  ref:
    - refs/heads/master

---
kind: secret
name: API_SITE_URL
get:
  path: drone/data/firstrussianny/SDA-React
  name: API_SITE_URL

---
kind: secret
name: DOCKER_HOST
get:
  path: drone/data/firstrussianny/SDA-API
  name: DOCKER_HOST

---
kind: secret
name: DOCKER_CA_CERT
get:
  path: drone/data/firstrussianny/SDA-API
  name: DOCKER_CA_CERT

---
kind: secret
name: DOCKER_CLIENT_CERT
get:
  path: drone/data/firstrussianny/SDA-API
  name: DOCKER_CLIENT_CERT

---
kind: secret
name: DOCKER_CLIENT_KEY
get:
  path: drone/data/firstrussianny/SDA-API
  name: DOCKER_CLIENT_KEY

---
kind: signature
hmac: cdd59a8a54cb7f132b41a87df4c3aa9fda29380b6c3dce38b4b3b7ca4a6cb413

...
