---
kind: pipeline
name: lint

steps:
- name: lint
  image: miki725/pre-commit

trigger:
  ref:
    - refs/heads/master
    - refs/pull/*/head

---
kind: pipeline
name: deploy

steps:
- name: deploy
  image: docker/compose:1.24.1
  environment:
    COMPOSE_PROJECT_NAME: sda-react
    MOUNT_PATH: /tmp/app
    API_SITE_URL:
      from_secret:  API_SITE_URL
  volumes:
    - name: docker_sock
      path: /var/run/docker.sock
  commands:
    - docker-compose build --pull
    - docker-compose up -d
    - timeout -t 10 docker-compose logs -f app || true

trigger:
  ref:
    - refs/heads/master

volumes:
  - name: docker_sock
    host:
      path: /var/run/docker.sock

---
kind: secret
name: API_SITE_URL
get:
  path: drone/data/firstrussianny/SDA-React
  name: API_SITE_URL

---
kind: signature
hmac: c980b3df817308006b9f5a9250d2742cc9b416f70dd2bd44f761245b64d2dd1c

...
