---
kind: pipeline
name: lint

steps:
- name: lint
  image: miki725/pre-commit

trigger:
  ref:
    - refs/heads/master
    - refs/pull/*/head

---
kind: pipeline
name: deploy

steps:
- name: deploy
  image: docker/compose:1.24.1
  environment:
    COMPOSE_PROJECT_NAME: sda-react
    MOUNT_PATH: /tmp/app
    API_SITE_URL:
      from_secret:  API_SITE_URL
    INSTAGRAM_SECRET:
      from_secret:  INSTAGRAM_SECRET
  volumes:
    - name: docker_sock
      path: /var/run/docker.sock
  commands:
    - docker-compose build --pull
    - docker-compose up -d

trigger:
  ref:
    - refs/heads/master

volumes:
  - name: docker_sock
    host:
      path: /var/run/docker.sock

---
kind: secret
name: API_SITE_URL
get:
  path: drone/data/firstrussianny/SDA-React
  name: API_SITE_URL

---
kind: secret
name: INSTAGRAM_SECRET
get:
  path: drone/data/firstrussianny/SDA-React
  name: INSTAGRAM_SECRET

---
kind: signature
hmac: b098a8a81255f433e5ab7ec7ff81505c988c984dbc045980108eae12e677f361

...
