---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 'master'
    hooks:
      - id: check-added-large-files
        args: [--maxkb=1024]
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: mixed-line-ending

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: 'master'
    hooks:
      - id: eslint
        args: ['--ext=.js,.ts,.tsx', .]
        additional_dependencies:
          - eslint@^7.17.0
          - eslint-config-prettier@^7.1.0
          - eslint-plugin-import@^2.22.1
          - eslint-plugin-jsdoc@^30.7.13
          - eslint-plugin-react@^7.22.0
          - '@typescript-eslint/eslint-plugin@^4.12.0'
          - '@typescript-eslint/eslint-plugin-tslint@^4.12.0'
          - '@typescript-eslint/parser@^4.12.0'

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.2.1
    hooks:
      - id: prettier
