---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 'master'
    hooks:
      - id: check-added-large-files
        args: [--maxkb=1024]
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: mixed-line-ending

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: 'master'
    hooks:
      - id: eslint
        args: ['--ext=.js,.ts,.tsx', .]
        additional_dependencies:
          - eslint@^8.10.0 # sync:package.json
          - eslint-config-prettier@^8.5.0 # sync:package.json
          - eslint-plugin-import@^2.25.4 # sync:package.json
          - eslint-plugin-jsdoc@^37.9.7 # sync:package.json
          - eslint-plugin-react@^7.29.3 # sync:package.json
          - '@typescript-eslint/eslint-plugin@^5.13.0' # sync:package.json
          - '@typescript-eslint/eslint-plugin-tslint@^5.13.0' # sync:package.json
          - '@typescript-eslint/parser@^5.13.0' # sync:package.json

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.2.1
    hooks:
      - id: prettier
