---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 'master'
    hooks:
      - id: check-added-large-files
        args: [--maxkb=1024]
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: mixed-line-ending

  # - repo: https://github.com/awebdeveloper/pre-commit-tslint/
  #   rev: 'master'
  #   hooks:
  #     - id: tslint
  #       files: \.(ts[x])$
  #       # https://github.com/pre-commit/pre-commit/issues/1064
  #       # https://github.com/ekalinin/nodeenv/issues/204
  #       additional_dependencies:
  #         - tslint
  #         - tslint-react
  #         - tslint-eslint-rules
  #         - typescript

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: 'master'
    hooks:
      - id: eslint
        # https://github.com/pre-commit/pre-commit/issues/1064
        # https://github.com/ekalinin/nodeenv/issues/204
        args: ['--ext=.js', .]
        additional_dependencies:
          - eslint@6.3.0
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.2.1
    hooks:
      - id: prettier
