version: "3.7"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        API_SITE_URL: $API_SITE_URL
    environment:
      - API_SITE_URL
    ports:
      - "${PUBLIC_PORT:-8080}:3000"
    volumes:
      - $PWD:${MOUNT_PATH:-/app}
    restart: always
