version: "3.7"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - INSTAGRAM_SECRET
    ports:
      - "8080:3000"
    volumes:
      - $PWD:${MOUNT_PATH:-/app}
